-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 09:26:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Provincias` (
  `id_Provincia` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Ciudades` (
  `id_Ciudades` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(45) NOT NULL,
  `Provincias_id_Provincia` INT NOT NULL,
  PRIMARY KEY (`id_Ciudades`),
  INDEX `fk_Ciudades_Provincias1_idx` (`Provincias_id_Provincia` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudades_Provincias1`
    FOREIGN KEY (`Provincias_id_Provincia`)
    REFERENCES `Pizzeria`.`Provincias` (`id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Codigo_postal` TINYINT(10) NOT NULL,
  `id_ciudad` INT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `id_provincia` INT NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Num_de_teléfono` INT NOT NULL,
  `Ciudades_id_Ciudades` INT NOT NULL,
  PRIMARY KEY (`id_Cliente`),
  INDEX `fk_Cliente_Ciudades1_idx` (`Ciudades_id_Ciudades` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Ciudades1`
    FOREIGN KEY (`Ciudades_id_Ciudades`)
    REFERENCES `Pizzeria`.`Ciudades` (`id_Ciudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pedidos` (
  `id_Pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `Fecha_Hora` DATETIME NOT NULL,
  `Reparto` TINYINT NOT NULL,
  `Fecha_Hora_reparto` DATETIME NULL,
  `Cantidad` INT NOT NULL,
  `Precio_total` FLOAT NOT NULL,
  `Cliente_id_Cliente` INT NOT NULL,
  PRIMARY KEY (`id_Pedido`),
  INDEX `fk_Pedidos_Cliente1_idx` (`Cliente_id_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`Cliente_id_Cliente`)
    REFERENCES `Pizzeria`.`Cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Productos` (
  `id_Productos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_producto` VARCHAR(45) NOT NULL,
  `Describción` VARCHAR(255) NULL,
  `Imagen` BLOB NULL,
  `Precio` FLOAT NOT NULL,
  `Pedidos_id_Pedido` INT NOT NULL,
  PRIMARY KEY (`id_Productos`),
  INDEX `fk_Productos_Pedidos1_idx` (`Pedidos_id_Pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Pedidos1`
    FOREIGN KEY (`Pedidos_id_Pedido`)
    REFERENCES `Pizzeria`.`Pedidos` (`id_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Tiendas` (
  `id_Tienda` INT NOT NULL AUTO_INCREMENT,
  `Dirección` INT NOT NULL,
  `Codigo_postal` INT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Ciudades_id_Ciudades` INT NOT NULL,
  PRIMARY KEY (`id_Tienda`),
  INDEX `fk_Tiendas_Ciudades1_idx` (`Ciudades_id_Ciudades` ASC) VISIBLE,
  CONSTRAINT `fk_Tiendas_Ciudades1`
    FOREIGN KEY (`Ciudades_id_Ciudades`)
    REFERENCES `Pizzeria`.`Ciudades` (`id_Ciudades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Empleados` (
  `id_Empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre_empleado` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Teléfono` INT NOT NULL,
  `Es_Repartidor` TINYINT NOT NULL,
  `Tiendas_id_Tienda` INT NOT NULL,
  PRIMARY KEY (`id_Empleado`),
  INDEX `fk_Empleados_Tiendas1_idx` (`Tiendas_id_Tienda` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Tiendas1`
    FOREIGN KEY (`Tiendas_id_Tienda`)
    REFERENCES `Pizzeria`.`Tiendas` (`id_Tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Categoría_producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Categoría_producte` (
  `id_Categoría_producte` INT NOT NULL AUTO_INCREMENT,
  `Nombre_categoría` VARCHAR(45) NULL,
  `Productos_id_Productos` INT NOT NULL,
  PRIMARY KEY (`id_Categoría_producte`),
  INDEX `fk_Categoría_producte_Productos1_idx` (`Productos_id_Productos` ASC) VISIBLE,
  CONSTRAINT `fk_Categoría_producte_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `Pizzeria`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Categoría_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Categoría_pizza` (
  `id_Categoría_pizza` INT NOT NULL,
  `Nombre_Categoria_pizza` VARCHAR(45) NOT NULL,
  `Categoría_producte_id_Categoría_producte` INT NOT NULL,
  PRIMARY KEY (`id_Categoría_pizza`),
  INDEX `fk_Categoría_pizza_Categoría_producte_idx` (`Categoría_producte_id_Categoría_producte` ASC) VISIBLE,
  CONSTRAINT `fk_Categoría_pizza_Categoría_producte`
    FOREIGN KEY (`Categoría_producte_id_Categoría_producte`)
    REFERENCES `Pizzeria`.`Categoría_producte` (`id_Categoría_producte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
