-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 10:40:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Óptica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Óptica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Óptica` DEFAULT CHARACTER SET utf8 ;
USE `Óptica` ;

-- -----------------------------------------------------
-- Table `Óptica`.`proveedors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Óptica`.`proveedors` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_prov` VARCHAR(45) NOT NULL,
  `dirección_prov` VARCHAR(255) NOT NULL,
  `teléfono_prov` INT NOT NULL,
  `fax_prov` INT NULL,
  `NIF_prov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Óptica`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `dirección_cliente` VARCHAR(255) NOT NULL,
  `teléfono_cliente` INT NOT NULL,
  `email_cliente` VARCHAR(45) NULL,
  `fecha_alta_cliente` DATE NOT NULL,
  `referral_de_cliente` INT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_empleado_UNIQUE` (`id_empleado` ASC) VISIBLE,
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Óptica`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_ventas`),
  INDEX `id_cl_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_cl`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Óptica`.`clientes` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Óptica`.`gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `id_prov_gafas` INT NOT NULL,
  `marca_gafas` VARCHAR(45) NOT NULL,
  `graduación_gafas` FLOAT NULL,
  `montura_gafas` VARCHAR(45) NOT NULL,
  `color_vidrio_gafas` VARCHAR(45) NULL,
  `precio_gafas` FLOAT NOT NULL,
  `ventas_id_ventas` INT NOT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `proveedor_idx` (`id_prov_gafas` ASC) VISIBLE,
  INDEX `fk_gafas_ventas1_idx` (`ventas_id_ventas` ASC) VISIBLE,
  CONSTRAINT `proveedor`
    FOREIGN KEY (`id_prov_gafas`)
    REFERENCES `Óptica`.`proveedors` (`id_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gafas_ventas1`
    FOREIGN KEY (`ventas_id_ventas`)
    REFERENCES `Óptica`.`ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
